version: '3'

services:

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth
    ports: 
      - '5432:5432'
    volumes:
      - database-data:/var/lib/postgresql/data

  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./:/usr/src/app
    depends_on:
      - postgres
volumes:
  database-data: