version: "3"

services:
  postgres-dev:
    image: postgres
    container_name: postgres-dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dev
    ports:
      - "5432:5432"
    volumes:
      - database-data-dev:/var/lib/postgresql/data

  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./:/usr/src/app
    depends_on:
      - postgres-dev
    entrypoint: ["npm", "run", "dev"]
volumes:
  database-data-dev:
